ACTUACION ESPECIAL DE FISCALIZACION RENDICION DE CUENTAS CONTRACTUAL PLATAFORMA SIA OBSERVA VIGENCIA 2025

Importacion de librerias

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import platform
import distro

from datetime import datetime

print(f"Las librerías se cargaron correctamente.")
print(f"Versión de Pandas: {pd.__version__}")
print(f"Versión de Numpy: {np.__version__}")
print(f"Sistema Operativo: {platform.system()} {platform.release()}")
print(f"Distribución Linux: {distro.name()} {distro.version()} ({distro.codename()})")

Las librerías se cargaron correctamente.
Versión de Pandas: 3.0.0
Versión de Numpy: 2.4.2
Sistema Operativo: Linux 6.14.0-37-generic
Distribución Linux: Ubuntu 24.04 (noble)

Configuraciones de visualizacion

In [29]:
pd.options.display.float_format = "{:,.2f}".format
pd.set_option("display.max_columns", None)
plt.style.use("ggplot")
print("configuraciones aplicadas")

configuraciones aplicadas

Gestion de rutas

In [30]:
BASE_DIR = os.path.dirname(os.getcwd())
RAW_DATA_PATH = os.path.join(BASE_DIR, "data", "raw")

PROCESSED_DATA_PATH = os.path.join(BASE_DIR, "data", "processed")

InformeBasico = os.path.join(RAW_DATA_PATH, "Informe_Basico.xlsx")
InformeExtendido = os.path.join(RAW_DATA_PATH, "Informe_Extendido.xlsx")

try:
    df_basico = pd.read_excel(InformeBasico)
    df_extendido = pd.read_excel(InformeExtendido)
    print(f"proyecto ubicado en:{BASE_DIR}")
    print(f"Archivos cargados Informe Basico {len(df_basico)}|  Informe Extendido {len(df_extendido)}"
    )

except Exception as e:
   
    print(f"Error {e}")

proyecto ubicado en:/home/wilo/Escritorio/auditoria_sia
Archivos cargados Informe Basico 14259|  Informe Extendido 14193

ENCABEZADOS Y ESTRUCTURA

In [31]:
print("--- ESTRUCTURA: INFORME BÁSICO ---")

print(df_basico.info())
print("\nPrimeros registros del Básico:")
display(df_basico.head(3))

print("\n" + "=" * 50 + "\n")

print("--- ESTRUCTURA: INFORME EXTENDIDO ---")
print(df_extendido.info())
print("\nPrimeros registros del Extendido:")
display(df_extendido.head(3))

--- ESTRUCTURA: INFORME BÁSICO ---
<class 'pandas.DataFrame'>
RangeIndex: 14259 entries, 0 to 14258
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Informe_Contratos_Basico  14259 non-null  object
 1   Unnamed: 1                14259 non-null  str
 2   Unnamed: 2                14259 non-null  object
 3   Unnamed: 3                14258 non-null  object
 4   Unnamed: 4                14259 non-null  object
 5   Unnamed: 5                14259 non-null  object
 6   Unnamed: 6                14259 non-null  object
 7   Unnamed: 7                14259 non-null  object
 8   Unnamed: 8                14259 non-null  str
 9   Unnamed: 9                14259 non-null  str
 10  Unnamed: 10               14259 non-null  str
 11  Unnamed: 11               14259 non-null  object
 12  Unnamed: 12               14259 non-null  str
 13  Unnamed: 13               14259 non-null  str
 14  Unnamed: 14               14259 non-null  str
 15  Unnamed: 15               14259 non-null  str
 16  Unnamed: 16               3861 non-null   str
 17  Unnamed: 17               14256 non-null  object
 18  Unnamed: 18               14256 non-null  str
 19  Unnamed: 19               14256 non-null  str
 20  Unnamed: 20               14259 non-null  str
dtypes: object(9), str(12)
memory usage: 2.3+ MB
None

Primeros registros del Básico:

,Informe_Contratos_Basico,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,NIT,ENTIDAD,VIGENCIA,CÓDIGOCONTRATO,VALOR INICIALCONTRATO,ADICIONES,LIBERACIONES,VALOR VIGENTE,FECHASUSCRIPCION,FECHAACTA DE INICIO,FECHATERMINACION,TIEMPO EJECUCIÓN,MODALIDADCONTRATACIÓN,CAUSAL CONTRATO,TIPOCONTRATO,FECHACREACIÓN,FECHATERMINACIONAMPLIADA,NIT,NOMBRE,TIPO,ESTADOCONTRATO
1,901685734,UMBRALED S.A.S E.S.P.,2025,UMB-01-2025,17676000,0,0,17676000,2025/01/01,2025/01/01,2025/12/31,364,CONTRATACIÓN DIRECTA,PRESTACIÓN DE SERVICIOS PROFESIONALES Y APOYO,Apoyo a la Gestión,2025/01/31 04:24:32 PM,NaN,24547202,MARIA LILIANA MONTES HOYOS,Contratista,Rendido
2,901685734,UMBRALED S.A.S E.S.P.,2025,UMB-02-2025,8846800,0,0,8846800,2025/01/01,2025/01/01,2025/12/31,364,CONTRATACIÓN DIRECTA,PRESTACIÓN DE SERVICIOS PROFESIONALES Y APOYO,Apoyo a la Gestión,2025/01/31 04:36:09 PM,NaN,900010878,GRUPO METRO Y CIA. LTDA,Contratista,Rendido

==================================================

--- ESTRUCTURA: INFORME EXTENDIDO ---
<class 'pandas.DataFrame'>
RangeIndex: 14193 entries, 0 to 14192
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Informe_Contratos_Extendido  14193 non-null  object
 1   Unnamed: 1                   14193 non-null  str
 2   Unnamed: 2                   14193 non-null  object
 3   Unnamed: 3                   14192 non-null  object
 4   Unnamed: 4                   14193 non-null  str
 5   Unnamed: 5                   14193 non-null  str
 6   Unnamed: 6                   14193 non-null  str
 7   Unnamed: 7                   14193 non-null  str
 8   Unnamed: 8                   14193 non-null  object
 9   Unnamed: 9                   14193 non-null  object
 10  Unnamed: 10                  14193 non-null  object
 11  Unnamed: 11                  14193 non-null  object
 12  Unnamed: 12                  14193 non-null  object
 13  Unnamed: 13                  14193 non-null  str
 14  Unnamed: 14                  14193 non-null  str
 15  Unnamed: 15                  14193 non-null  str
 16  Unnamed: 16                  14193 non-null  object
 17  Unnamed: 17                  14193 non-null  str
 18  Unnamed: 18                  14193 non-null  str
 19  Unnamed: 19                  14193 non-null  object
 20  Unnamed: 20                  14193 non-null  str
 21  Unnamed: 21                  14193 non-null  str
 22  Unnamed: 22                  14158 non-null  str
 23  Unnamed: 23                  14193 non-null  object
 24  Unnamed: 24                  14193 non-null  str
 25  Unnamed: 25                  14193 non-null  object
 26  Unnamed: 26                  14193 non-null  object
 27  Unnamed: 27                  14193 non-null  str
dtypes: object(13), str(15)
memory usage: 3.0+ MB
None

Primeros registros del Extendido:

,Informe_Contratos_Extendido,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,NIT,ENTIDAD,VIGENCIA,CÓDIGOCONTRATO,OBJETOCONTRATO,FECHASUSCRIPCION,FECHAACTA DE INICIO,FECHATERMINACION,TIEMPO EJECUCIÓN,VALOR INICIALCONTRATO,ADICIONES,LIBERACIONES,VALOR VIGENTE,MODALIDADCONTRATACIÓN,CAUSAL CONTRATO,TIPOCONTRATO,NIT,NOMBRE,TIPO,NIT,NOMBRE,TIPO,Nombre del Rubro,Apropiación Inicial,Origen Recursos,CDPS,RPS,FECHACREACIÓN
1,901685734,UMBRALED S.A.S E.S.P.,2025,UMB-01-2025,ARRENDAMIENTO DE INMUEBLE CON DESTINACION COME...,2025/01/01,2025/01/01,2025/12/31,364,17676000,0,0,17676000,CONTRATACIÓN DIRECTA,PRESTACIÓN DE SERVICIOS PROFESIONALES Y APOYO,Apoyo a la Gestión,24547202,MARIA LILIANA MONTES HOYOS,Contratista,1088332330,JORGE WILLIAM GONZALEZ TAMAYO,Interno,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,68266800,Recursos Propios,20250001,20250001,2025/01/31 04:24:32 PM
2,901685734,UMBRALED S.A.S E.S.P.,2025,UMB-02-2025,"CONTRATAR LA IMPLEMENTACION, PUESTA EN FUNCION...",2025/01/01,2025/01/01,2025/12/31,364,8846800,0,0,8846800,CONTRATACIÓN DIRECTA,PRESTACIÓN DE SERVICIOS PROFESIONALES Y APOYO,Apoyo a la Gestión,900010878,GRUPO METRO Y CIA. LTDA,Contratista,1088332330,JORGE WILLIAM GONZALEZ TAMAYO,Interno,PAQUETES DE SOFTWARE,9072000,Recursos Propios,20250003,20250003,2025/01/31 04:36:09 PM